### ISSUE TITLE
latest commits recreated volumes?

### ISSUE THREAD

**Issue by mathematicalmichael** [sachua/mlflow-docker-compose#3]
what happened with the last few commits, exactly? I noticed you updated an image to address "command not found" but I think in doing so all the data in my volume was wiped out. i lost over an hour trying to find it and eventually couldn't (and noticed the disk shrank), had to get it from a daily snapshot (thank goodness for that).

is this an issue with my filesystem / docker somehow? or are there commands in the docker compose file that somehow could have removed the data?

I'm noticing the files were in `docker/overlay2/l/` instead of `docker/volumes/` ... that makes me suspect that my previous deployment was never writing to the `minio_data` volume at all but rather to the overlay filesystem inside the container, which is why creating a new container made the files disappear. that would explain why upgrading made it look like all my files disappeared...the container changed.

**Comment by sachua** [comment]
The reason why `mc` was required is to automate the creation the `mlflow` bucket that will be used as the artifact store for MLflow when the MinIO service is first initialised. Using the official minio stack will not solve this issue. 
However, I have changed the `mc` service to use a `wait-for-it.sh` script to check in MinIO is ready before creating the bucket, instead of relying on the `nc` which was removed in the newer versions of `mc` images, so it no longer depends on an older image!
Doing a basic search in GitHub I found a few repos such as https://github.com/ymym3412/mlflow-docker-compose and https://github.com/Toumash/mlflow-docker, but I have not used them personally. You can check them out if you're interested. Of course, I will still try to support this repo to the best of my ability.
