### ISSUE TITLE
Question on MLflow setup

### ISSUE THREAD

**Issue by jamesee** [sachua/mlflow-docker-compose#8]
Hi SongAnn,

Thank you for the wonderful mlflow-docker-compose repo. It is exactly what I am looking for.

Question:

1. With reference to Example(4), it seems the minio server to s3 bucket on AWS. May I know how I should setup if I just wanted to store the artifacts on localhost file directory?

Look forward to your reply soon.

Regards,
James

**Comment by sachua** [comment]
Hi James, example 4 is just to set the MinIO credentials for mlflow and if I'm not wrong boto3 as well so that they can access the MinIO S3 object store container that you spun up when running `docker-compose up`, so the MinIO server is actually running in your local machine and the artifacts are stored locally in `minio_data`.
If you want to use a local file path instead, I think you will have to change the --default-artifact-root flag, if you remove the flag it will default to `./mlruns` directory inside the container, then you can mount a volume from your local machine to the `./mlruns` directory, but in this case, you might as well just run mlflow in your local machine instead.
You can check out https://www.mlflow.org/docs/latest/tracking.html#id69 for more info on the artifact store.

**Comment by jamesee** [comment]
Hi SoongAnn,

Thank you very much for the prompt response.

I am testing out your repo, but faced the following errors when I execute example-(6). Do you know why it is complaining of " No module named 'sklearn.linear_model.coordinate_descent'"?

$ mlflow models serve -m s3://mlflow/0/7b9bfff0a71f425094d77bb33b2e5511/artifacts/model -p 1234


<img width="1680" alt="Screenshot 2021-12-28 at 15 18 41" src="https://user-images.githubusercontent.com/37786118/147539871-272e7c1e-3e56-4d61-8a0e-9d735094c925.png">
<img width="1680" alt="Screenshot 2021-12-28 at 15 24 05" src="https://user-images.githubusercontent.com/37786118/147539887-68bd95cb-86d7-4023-8eff-99cdf8103169.png">

**Comment by sachua** [comment]
I just tried it myself and it is working fine for me... not sure why it is not working for you, it might have something to do with your environment set up.. perhaps try running the mlflow model serve command from your mlflow environment and not the generated environment? If not I guess you could create an issue in the mlflow github for better guidance.
